use_frameworks!

target 'FAIHASDSH_Example' do
  pod 'FAIHASDSH', :path => '../'

  target 'FAIHASDSH_Tests' do
    inherit! :search_paths

    
  end
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
#      config.build_settings['CODE_SIGNING_REQUIRED'] = ""
#      config.build_settings['CODE_SIGNING_ALLOWED'] = ""
#    end
#  end
#end
